// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		int n = Integer.parseInt(args[0]);
		
		int counter = 0;
		int i = 0;
		int j = 0;
		double ratio = 0;
		
		while (counter<n) {
			double random = (double) Math.random();

			if (random > 0.5) {
				i++;
			} else {
				j++;
			}
			counter++;	
		}

		if (i>j) {
			ratio = (double) j/i;
		} else {
			ratio = (double) i/j;
		}

		System.out.println("> 0.5: "+i);
		System.out.println("<= 0.5: "+j);
		System.out.println(ratio);    
	}
}



//Math.random
//% java TestRandom 100
//> 0.5: 47 times
//<= 0.5: 53 times
//Ratio: 0.8867924528301887